FROM ros:foxy-ros-base

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y ros-foxy-navigation2 \
                       ros-foxy-nav2-bringup \
                       ros-foxy-turtlebot3*